# 데이터 경로
data_dir: "/opt/ml/input/data/train"
mode: "experiment" # experiment, inference
submission_path : "../submission"
submission_name : "test_submission.csv"

# 모델 저장 경로 model_name : "Multi-DAE_v2.pt"
model_dir : "./saved_model"
name : RecVAE_v4

# 사용할 모델
model : RecVAE
model_config : RecVAE_config

# 사용할 데이터셋
dataset : MatrixDataset

seed : 22

# mlflow
experiment_name : NNI_experiment
run_name : hyperparameter_tunning
user : yujeong