# 데이터 경로
data_dir: "/opt/ml/input/data/train"

submission_path : "../submission"
submission_name : "test_submission.csv"

# 모델 저장 경로 model_name : "Multi-DAE_v2.pt"
model_dir : "./saved_model"
name : NGCF

# 사용할 모델
model : NGCF
model_config : NGCF_config

# 사용할 데이터셋
dataset : GraphDataset

seed : 22