trainer: MatrixBasedTrainer
use_data_loader: yes
optimizer: adam
preprocessor: AEDataset
weight_decay: 0.00
valid_samples: 10  # 검증에 사용할 sample 수
lr: 0.001
batch_size: 128
num_epochs: 50
num_workers: 2


p_dims:
  - 100
  - 200
  - 400
dropout_rate: 0.5
anneal_cap: 0.2
total_anneal_steps: 200000
