trainer: MatrixBasedTrainer
use_data_loader: yes
optimizer: Adam
preprocessor: AEDataset
weight_decay: 0.01
valid_samples: 10  # 검증에 사용할 sample 수
lr: 0.0005
batch_size: 500
num_epochs: 200
num_workers: 2

hidden_dim: 600
latent_dim: 200
dropout_rate: 0.7
gamma: 0.0005
beta: None

e_num_epochs: 2
d_num_epochs: 1