data_dir : "../../input/data/train/"
output_idr : "output/"
data_name : "Ml"

# model args
model_name : "Finetune_full"
hidden_size : 64
num_hidden_layers : 2
num_attention_heads : 2
hidden_act : "gelu"
attention_probs_dropout_prob : 0.5
hidden_dropout_prob : 0.5
initializer_range : 0.02
max_seq_length : 50

# train args
lr :   0.001
batch_size :  256
epochs :  200
no_cuda : false
log_freq :  1
seed : 42

weight_decay :  0.0
adam_beta1 :  0.9
adam_beta2 :  0.999
gpu_id : "0"

using_pretrain : false